title: "CIAMOD"
description: "Computational methods and AI for moduli spaces"
theme: jekyll-theme-minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
kramdown:
  syntax_highlighter: rouge
